repos:
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: "v0.6.4"
  #   hooks:
  #     - id: ruff
  #       args: [--fix]
  #     - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      # - id: mixed-line-ending
      # - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       exclude: tests/
  #       args: ["-c", "pyproject.toml"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
        files: requirements.*\.txt$
